apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

namespace: stateful-app

configMapGenerator:
- name: app-configmap
  envs:
  - app-eks/.env
- name: postgres-configmap
  envs:
  - postgres/.env
- name: jaeger
  files:
  - configs/jaeger-ui.json
- name: otel-collector
  files:
  - configs/otel-collector.yaml
- name: prometheus
  files:
  - configs/prometheus.yaml
  
resources:
  - namespace.yaml
  - app-eks/bundle.yaml
  - app-eks/jaeger.yaml
  - app-eks/prometheus.yaml
  - app-eks/otel-collector.yaml
  - postgres/bundle.yaml

images:
  - name: postgres
    newName: postgres
    newTag: '13.4'
  - name: redis
    newName: redis
    newTag: '7.0.0'
  - name: app
    newName: localhost:5000/stateful-app
    newTag: '6.0'
