apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

namespace: stateful-app

configMapGenerator:
- name: app-configmap
  envs:
  - app-eks/.env
- name: postgres-configmap
  envs:
  - postgres/.env

resources:
  - namespace.yaml
  - app-eks/bundle.yaml
  - postgres/bundle.yaml

images:
  - name: postgres
    newName: postgres
    newTag: '13.4'
  - name: redis
    newName: redis
    newTag: '7.0.0'
  - name: app
    newName: localhost:5000/stateful-app
    newTag: '6.0'
  - name: app-eks
    newName: 904979830020.dkr.ecr.eu-central-1.amazonaws.com/stateful-app
    newTag: '11.0'
