kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
- role: worker
  extraMounts:
  - hostPath: ./kind-pv
    containerPath: /var/kind-pv
- role: worker
  extraMounts:
  - hostPath: ./kind-pv
    containerPath: /var/kind-pv
- role: worker
  extraMounts:
  - hostPath: ./kind-pv
    containerPath: /var/kind-pv
