apiVersion: v1
kind: Service
metadata:
  labels:
    app: jaeger
  name: jaeger
spec:
  ports:
    - name: "16686"
      port: 16686
      targetPort: 16686
    - name: "4318"
      port: 4318
      targetPort: 4318
    - name: "14250"
      port: 14250
      targetPort: 14250
  selector:
    app: jaeger
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: jaeger
  name: jaeger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jaeger
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: jaeger
    spec:
      containers:
        - args:
            - --query.ui-config
            - /etc/jaeger/jaeger-ui.json
          env:
            - name: METRICS_STORAGE_TYPE
              value: prometheus
            - name: PROMETHEUS_SERVER_URL
              value: http://prometheus:9090
          image: jaegertracing/all-in-one:1.35
          name: jaeger
          ports:
            - containerPort: 16686
            - containerPort: 4318
            - containerPort: 14250
          resources:
            limits:
              cpu: 800m
              memory: 3Gi
            requests:
              cpu: 800m
              memory: 3Gi
          volumeMounts:
          - name: jaeger
            mountPath: /etc/jaeger/jaeger-ui.json
            subPath: jaeger-ui.json
      volumes:
        - name: jaeger
          configMap:
            name: jaeger
      restartPolicy: Always
status: {}
