apiVersion: v1
kind: Service
metadata:
  name: app
  labels:
    app: app
spec:
  ports:
  - port: 80
    name: app
  clusterIP: None
  selector:
    app: app
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: app
  namespace: stateful-app
spec:
  serviceName: "app"
  replicas: 3
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: app
        envFrom:
        - configMapRef:
            name: app-configmap
        ports:
        - containerPort: 8080
          name: app
        volumeMounts:
        - name: app-data
          mountPath: /usr/app
  volumeClaimTemplates:
  - metadata:
      name: app-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      #TODO
      #storageClassName: manual
      resources:
        requests:
          storage: 1Gi